### ISSUE TITLE
Link the Login Screen to the Backend

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#10]
## Idea

We have the login screen almost done, the last step that we need to complete is having the form fulfill an HTTP request to our backend. The backend is [here](https://github.com/fairfield-programming/), and the login endpoint is `/user/login`. 

## Todo
- [ ] Send a post request to `/user/login`
- [ ] Save the token and user info to the cookies 
- [ ] Redirect the user to the `/user` page if they're logged in

**Comment by Lordhacker756** [comment]
Hello @William-McGonagle 👋🏻, I'd love to work on the issue, but I'd be needing a little help in understanding, what language is the backend in, actually I know how to use PHP as backend but I'd love to learn about using how to use cookies to log the user in, it would be a great learning experience😄

**Comment by William-McGonagle** [comment]
Hey @Lordhacker756, the backend is written in Node.js but all of the code for that is already done. All that you need to build is a POST XMLHttpRequest that is sent to the `/user/login` endpoint on the backend server. The backend server is at this address, `https://fairfield-programming.herokuapp.com` and if you could even do that, it would be great!

**Comment by Lordhacker756** [comment]
@William-McGonagle, This looks interesting, can you please assign this to me😄

**Comment by Lordhacker756** [comment]
@William-McGonagle Hello!👋🏻, I've added the code for sending the POST request to the code by adding the script to the ```src/auth/login/index.html``` , but how should I test that, If possible can we connect over some conversation platform like LinkedIn or Instagram, I'd really love to understand about how NodeJs backend works🙏🏻

**Comment by William-McGonagle** [comment]
Hey @Lordhacker756, thank you for your help, we can connect via our discord server. The link to join it is [here](https://discord.gg/r2JnDXvrWt).

**Comment by MassiGy** [comment]
Hey There, 
I'am new to open source, and I want to help you guys to be more familiar with this ecosystem.
I'am an express/nodejs backend web developer, so I can actually resolve the problem with the local strategy, but before that, I need to know what is your routes and database (to store sessions).

Thanks

**Comment by William-McGonagle** [comment]
Hey @MassiGy,

All of our database and server information is [available here](https://github.com/fairfield-programming/backend-server). 

Thanks

**Comment by MassiGy** [comment]
I think I could do it, could you please assign it to me ? 
If my understanding is correct, you've now have the frontend and the backend running separately, and you need to make the connection between them.
And as you've said, all the code is there, we just need to set the APIs calls.

**Please correct me if I'am wrong.**

Thanks.

**Comment by MassiGy** [comment]
Also please add me to the contributors, so as I can push code from my local machine, for this repo and also the backend one.

Thanks.

**Comment by William-McGonagle** [comment]
Hey @MassiGy,

The way that contributing works is that you fork the project and then send a pull request when you think your code is ready to be used in the main project. Github makes you a contributor once your code becomes part of the project. 

We can only give you privileges to push code directly if you become part of the team. If you want to, just let us know- we would love to have you. 

Thanks,
William McGonagle

**Comment by MassiGy** [comment]
Thanks for the hint !

**Comment by MassiGy** [comment]
Hey @William-McGonagle @NikitaLejnev @NeilChaudhari , 

I've solved the problem of linking the login form with the backend (route handler), and I've tested it in my local machine by omitting the redirection performed via the file `/src/routes/index.js`, so as I can use the `https://localhost:8080` server as the backend since my tweaks to the code base are just present locally. 

Everything is working, I'am able to see the `req.body` fields, and also the response was no longer `Not All Parameters Given` but it is now responding me by `Account Not Found` which makes sens since I had no account in the database, and also the signup form do not work as well, XD.

### How to get my tweaks into the code base ?
1. Accept my pull request to this github repo (the frontend one), so as the form & inputs of the login page are setup correctly.
2. Accept all my pull request**s** on the backend repo, so as the `/src/index.js` & the `/src/routes/User/Account/login.js` files are setup correctly as well.

**Please let me know if something went wrong.**

Hope that this will fix it.
Massiles.

**Comment by MassiGy** [comment]
Hey @William-McGonagle @NikitaLejnev @NeilChaudhari ,

I've solved the other tasks, and I tested them, I'am able to send a request form the front-end to the backend, and handle it in the backend, and by saying that I mean: 
1. Checking the user credentials
2. Create a user specific `token`
3. Send this token to the user and store it in `httpsOnly cookies`
4. Redirect the user to `/user`
4. Send this `cookie` back and forth in each new request.

My code is available in my pull request on the backend repository. 
I think that this fixes this issues.

**Please refer to me if something is wrong**.

Massiles.

**Comment by William-McGonagle** [comment]
@MassiGy Thank you so much for the pull request. Your code looks great and we would love to have you on the team!

**Comment by MassiGy** [comment]
thank you so much for the good feedback @William-McGonagle !
And yeah, I tried to chat with you in Linkedin to know more about the role & responsibilities of being in your team.

My Linkedin profile : linkedin.com/in/massigy/

Thanks again.
Massiles.
