### ISSUE TITLE
📝 Add Social Media to Footer

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#8]
## Idea
From this blog post, we got a lot of comments saying that we need to add a bit to our website. One of the things we need to add is a better footer, with icons. The footer can be found on the main page inside of the footer area. 

## Todo
- [ ] Add blog link to footer with icon - [blog link](https://blog.fairfieldprogramming.org)
- [ ] Add discord link to footer with icon - [discord link](https://discord.gg/r2JnDXvrWt)
- [ ] Add github link to footer with icon - [github link](https://github.com/fairfield-programming)

**Comment by Lordhacker756** [comment]
Hello👋🏻 there is this issue still open?
If it is please assign it to me, I would love to work on this😄

**Comment by William-McGonagle** [comment]
Hey @Lordhacker756, sadly this issue is closed. You can work on the login page if you would like though! :)

**Comment by Lordhacker756** [comment]
@William-McGonagle Yes, I'd love to work on it, is there an open issue for the login page?

**Comment by William-McGonagle** [comment]
@Lordhacker756 I just made an issue for it [here](#10), you'll have to comment on the issue for me to assign it. Thanks!

#10
